spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frank
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8888